services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: myspeak_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
      - "10000:10000/udp"
      - "10000:10000/tcp"
    volumes:
      - ./server:/app
      - /app/node_modules
      - sqlite_data:/app/data
    environment:
      NODE_ENV: development
      DATABASE_URL: file:./data/my-speak.db
      PORT: 3001
    networks:
      - myspeak_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: myspeak_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - myspeak_network

volumes:
  sqlite_data:

networks:
  myspeak_network:
    driver: bridge