services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    volumes:
      - sqlite_data:/app/data
    ports:
      - "3001:3001"
      - "10000-10100:10000-10100/udp"
    networks:
      - myspeak_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    networks:
      - myspeak_network
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  sqlite_data:

networks:
  myspeak_network:
    driver: bridge