FROM node:20-alpine

WORKDIR /app

# 安装系统依赖
RUN apk add --no-cache openssl

# 复制 package.json
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制 prisma schema
COPY prisma ./prisma/

# 生成 Prisma 客户端
RUN npx prisma generate

# 暴露端口
EXPOSE 3001 10000-10100/udp

# 启动命令
CMD ["npm", "run", "dev"]
